Load in NumPy

In [1]:
import numpy as np

The Basics

In [15]:
a=np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [3]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
#Get DImension
a.ndim

1

In [5]:
b.ndim

2

In [6]:
#Get shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [11]:
#get type
a.dtype

dtype('int16')

In [12]:
#get size
a.size

3

In [16]:
a.itemsize

4

In [14]:
b.itemsize

8

In [19]:
a.nbytes #a.size*a.itemsize

12

#Accessing/changing specific elements,rows,columns,etc

In [20]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
#get specific element [r,c]
a[1]

array([ 8,  9, 10, 11, 12, 13, 14])

In [22]:
a.shape

(2, 7)

In [23]:
a[1][1]

9

In [24]:
a[1,5]

13

In [26]:
a[-2,-2]

6

In [27]:
#get specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
#get specific column
a[:,0]

array([1, 8])

In [29]:
#getting bit tougher [startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [30]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [32]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [34]:
#3D example
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [36]:
#get specific element
b[0,1,:]

array([3, 4])

In [38]:
b[:,1,:]=[[9,9],[8,8]]

In [39]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

#Initialising Different types of Arrays

In [45]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
#All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [49]:
#Any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [52]:
#Any  other number(full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [54]:
#random decimal numbers
np.random.rand(4,2)

array([[0.51091269, 0.8598377 ],
       [0.95648529, 0.44680439],
       [0.18034286, 0.25422127],
       [0.90630881, 0.87876871]])

In [57]:
np.random.random_sample(a.shape)

array([[0.6699503 , 0.67856927, 0.29816966, 0.19044009, 0.89163141,
        0.73832581, 0.27028664],
       [0.01788894, 0.06077749, 0.24279219, 0.37299317, 0.45899586,
        0.93814044, 0.25977986]])

In [63]:
#random integer values
np.random.randint(-4,8,size=(3,3))

array([[-4,  6,  4],
       [ 5, -3, -1],
       [ 2,  6,  2]])

In [65]:
#identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [73]:
#repeat an array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [74]:
np.array([5,5])

array([5, 5])

In [75]:
output=np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [78]:
z=np.zeros((3,3))
z[1,1]=9

In [79]:
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [80]:
output[1:4,1:4]=z

In [81]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Be careful while copying arrays

In [95]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)

[1 2 3]


In [96]:
print(b)

[100   2   3]


### Mathematics

In [97]:
a=np.array([1,2,3,4])

In [98]:
a+2

array([3, 4, 5, 6])

In [99]:
a-2

array([-1,  0,  1,  2])

In [100]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [101]:
a+=2

In [102]:
a

array([3, 4, 5, 6])

In [103]:
b=np.array([2,3,1,2])

In [104]:
a+b

array([5, 7, 6, 8])

In [105]:
a**2

array([ 9, 16, 25, 36], dtype=int32)

In [106]:
#trignometric
np.cos(a)
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

### Linear ALgebra

In [108]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [109]:
b=np.full((3,2),2)

In [110]:
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [113]:
a.dot(b)
#or
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [115]:
#Find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### statistics

In [121]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [122]:
np.min(stats,axis=0)

array([1, 2, 3])

In [126]:
np.max(stats)

6

In [127]:
np.max(stats,axis=1)

array([3, 6])

### Reorganising arrays

In [128]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [141]:
after=before.reshape((4,2,1))

In [142]:
after

array([[[1],
        [2]],

       [[3],
        [4]],

       [[5],
        [6]],

       [[7],
        [8]]])

### Vertical Stacking matrices

In [144]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

### Horizontal stack

In [145]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
h1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [146]:
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Load Data from file 

In [164]:
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean masking and advance index

In [165]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [166]:
##you can index using list
a=np.array([1,2,3,4])
a[[0,2]]

array([1, 3])

In [172]:
np.all(filedata>=1,axis=0)

array([False, False, False])

In [173]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])